FROM node:22-alpine

WORKDIR /app
COPY package*.json ./
RUN npm i

COPY . .
RUN npx prisma generate

EXPOSE 4000

CMD ["sh", "-c", "npx prisma migrate dev --name init && npm run start:dev"]
