services:

  postgres:
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    restart: always
    depends_on:
      - postgres
    networks:
      - app-network
    ports:
      - "4000:4000"
    volumes:
      - ./src:/app/src

networks:
  app-network:

volumes:
  postgres-data:
