FROM node:22-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm install --only=production

COPY . .
RUN npx prisma generate

FROM node:22-alpine

WORKDIR /app
COPY --from=build /app /app

EXPOSE 4000

CMD ["sh", "-c", "npx prisma migrate dev --name init && npm run start:prod"]
