export const CRYPT_SALT = 'CRYPT_SALT';
export const JWT_SECRET_KEY = 'JWT_SECRET_KEY';
export const JWT_SECRET_REFRESH_KEY = 'JWT_SECRET_REFRESH_KEY';
export const TOKEN_EXPIRE_TIME = 'TOKEN_EXPIRE_TIME';
export const TOKEN_REFRESH_EXPIRE_TIME = 'TOKEN_REFRESH_EXPIRE_TIME';
